name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always


permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: main
        submodules: 'recursive'
    - uses: actions/checkout@v3
      with:
        repository: MJ23333/ArknightsStory
        ref: gh-pages
        path: gh-pages
    - name: clear
      run: |
        cd ./gh-pages
        git rm -r *
        cd ..
    - name: copy file
      run: cp "main/ArknightsGameData/zh_CN/gamedata/excel/story_review_table.json" "main/json/zh_CN/story_review_table.json"
    - name: Build site
      run: |
        cd main
        cargo run
    - name: copy result
      run: |
        cp ./main/out/* ./gh-pages -r
        cd ./gh-pages
        git config --global user.email mengji233@gmail.com
        git config --global user.name update_bot
        git add -A
        git commit --allow-empty -m 'Build'
        git push
